name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Push
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        ocaml-version: [ '4.09.0']
    steps:
      - uses: actions/checkout@master
      - uses: avsm/setup-ocaml@v1.0
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - name: Install dependencies
        run: |
          opam install dune
          opam install ppx_inline_test
      - name: Build
        run: opam exec -- dune build @install
      - name: Test  
        run: opam exec -- dune runtest
